name: Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'GitForWindowsHelper/**'

jobs:
  deploy:
    if: github.event.repository.fork == false
    environment: deploy-to-azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Azure/functions-action@v1
        with:
          app-name: GitForWindowsHelper
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
